apiVersion: v1
kind: Namespace
metadata:
  name: pms
  labels:
    app.kubernetes.io/name: pms
    app.kubernetes.io/part-of: pms-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: pms-staging
  labels:
    app.kubernetes.io/name: pms
    app.kubernetes.io/part-of: pms-platform
    environment: staging
